import day7_part2_solution
import os

def test_part2_example():
    example_input = """.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............
"""
    with open('test_input_part2.txt', 'w') as f:
        f.write(example_input)
    
    result = day7_part2_solution.solve('test_input_part2.txt')
    print(f"Test Result: {result}")
    
    assert result == 40, f"Expected 40, got {result}"
    print("Test Passed!")
    
    os.remove('test_input_part2.txt')

if __name__ == "__main__":
    test_part2_example()
