import day7_solution
import os

def test_example():
    example_input = """.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............
"""
    with open('test_input.txt', 'w') as f:
        f.write(example_input)
    
    result = day7_solution.solve('test_input.txt')
    print(f"Test Result: {result}")
    
    assert result == 21, f"Expected 21, got {result}"
    print("Test Passed!")
    
    os.remove('test_input.txt')

if __name__ == "__main__":
    test_example()
